[tool.poetry]
name = "zkstats-test"
version = "0.1.0"
description = ""
authors = ["exfinen"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
zkstats = {path = "./zk-stats-lib"}
torch = "^2.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

